code cleanup

diff --git a/ybs b/ybs
--- a/ybs
+++ b/ybs
@@ -23,7 +23,7 @@
 . /usr/lib/ybs/funcs
 
 ybs_show_usage() {
-	cat <<EOF
+    cat <<EOF
 $0  
 
 Usage: $0 command [options] pkg1 [pkg2 ...]
@@ -48,7 +48,7 @@ Options for build:
     --fetch                 Break after download source tarball
     --unpack                Break after unpack source tarball
     --patch                 Break after patch source
-    --config                Break after configure	
+    --config                Break after configure    
     --make                  Break after make a.k.s compile
     --check                 Break after make check/test
     --mkinstall             Break after make install    
@@ -64,71 +64,71 @@ mkdir -p $YPK_DEST $WORKING_FIELD
 i=0
 j=0
 for arg in $@;do 
-	# Remove blank in string	
-	arg=$(echo $arg |tr -d '[:blank:]')
-	case $arg in
-		-*) argvs[${j}]="$arg"
-		    let j++	;;
-		*)  args[${i}]="$arg"
-		    let i++
-	esac
+    # Remove blank in string    
+    arg=$(echo $arg |tr -d '[:blank:]')
+    case $arg in
+      -*) argvs[${j}]="$arg"
+          let j++    ;;
+       *)  args[${i}]="$arg"
+          let i++
+    esac
 done
 
 for i in ${argvs[@]}; do
-	case ${i} in
-	  -p|--pretend) PRETEND="yes"       ;;
-	  -F|--force)   FORCE_INSTALL="yes" ;;
-	  --fetch)      BREAK="fetch"       ;;
-	  --unpack)     BREAK="unpack"      ;;	
-	  --patch)      BREAK="patch"       ;;	
-	  --config)     BREAK="config"      ;;
-	  --make)       BREAK="make"        ;;
-	  --check)      BREAK="check"       ;;
-	  --mkinstall)  BREAK="mkinstall"   ;;
-	  --package)    BREAK="package"     ;;
-	  -h|--help|-s|--search| \
-          -d|--download|-r|--remove| \
-          -i|--build|-is|--build-single| \
-          -w|--showpbs|-wr|--whatrequires|--sync|--info) ;;
- 		*)      msg "ybs: ${i} is not a ybs options. See ybs --help."
-			msg ""
-			case ${i##*-} in
-			  f*) msg "Did you mean: --fetch"  ;;
-			  u*) msg "Did you mean: --unpack" ;;
-              p*) msg "Did you mean: --patch --package"  ;; 
-              c*) msg "Did you mean: --config --check" ;;
-              m*) msg "Did you mean: --make --mkinstall" ;;
-               *) msg "Did you mean one of these?"
-                  msg "--fetch --unpack --patch --config --make --check --mkinstall --package"
-			esac	
-			exit 1
-	esac
+    case ${i} in
+      -p|--pretend) PRETEND="yes"       ;;
+      -F|--force)   FORCE_INSTALL="yes" ;;
+      --fetch)      BREAK="fetch"       ;;
+      --unpack)     BREAK="unpack"      ;;    
+      --patch)      BREAK="patch"       ;;    
+      --config)     BREAK="config"      ;;
+      --make)       BREAK="make"        ;;
+      --check)      BREAK="check"       ;;
+      --mkinstall)  BREAK="mkinstall"   ;;
+      --package)    BREAK="package"     ;;
+      -h|--help|-s|--search| \
+      -d|--download|-r|--remove| \
+      -i|--build|-is|--build-single| \
+      -w|--showpbs|-wr|--whatrequires|--sync|--info) ;;
+            *)      msg "ybs: ${i} is not a ybs options. See ybs --help."
+             msg ""
+              case ${i##*-} in
+               f*) msg "Did you mean: --fetch"  ;;
+               u*) msg "Did you mean: --unpack" ;;
+               p*) msg "Did you mean: --patch --package" ;; 
+               c*) msg "Did you mean: --config --check" ;;
+               m*) msg "Did you mean: --make --mkinstall" ;;
+                *) msg "Did you mean one of these?"
+                   msg "--fetch --unpack --patch --config --make --check --mkinstall --package"
+            esac    
+            exit 1
+    esac
 done
 
 case "${1}" in
 -info|--info)
-	# Show build info
-	grep -v ^# "/etc/ybs.conf" |sed '/^$/d'
-	;;
+    # Show build info
+    grep -v ^# "/etc/ybs.conf" |sed '/^$/d'
+    ;;
 
 -s|--search)
-	msg_ "* Searching for "
-	wmsg_ "${args[@]} "
-	msg "..."
-	for i in ${args[@]}; do
-		ybs_search $i
-	done
-	;;
+    msg_ "* Searching for "
+    wmsg_ "${args[@]} "
+    msg "..."
+    for i in ${args[@]}; do
+        ybs_search $i
+    done
+    ;;
 
 -d|--download)
-	check_root
-	msg_ "* Source downloading "
-	wmsg_ "${args[@]} "
-	msg "..."
-	for i in ${args[@]}; do
-		ybs_download $i
-	done
-	;;
+    check_root
+    msg_ "* Source downloading "
+    wmsg_ "${args[@]} "
+    msg "..."
+    for i in ${args[@]}; do
+        ybs_download $i
+    done
+    ;;
 
 -i|--build)
     check_root
@@ -139,89 +139,89 @@ case "${1}" in
     ;;
 
 -is|--build-single) 
-	check_root
-	# Build single package
-	msg_ "* Installing "
-	wmsg_ "${args[@]} "
-	msg "..."
-	FORCE_INSTALL="yes"
-	for i in ${args[@]}; do
-		if [ "x$TERM" != "xlinux" ]; then
-			echo -ne "\033]0;ybs working: ${i}\007"; ybs_build_raw $i || exit 1
-		else
-			ybs_build_raw $i || exit 1
-		fi
-	done
-	;;
+    check_root
+    # Build single package
+    msg_ "* Installing "
+    wmsg_ "${args[@]} "
+    msg "..."
+    FORCE_INSTALL="yes"
+    for i in ${args[@]}; do
+        if [ "x$TERM" != "xlinux" ]; then
+            echo -ne "\033]0;ybs working: ${i}\007"; ybs_build_raw $i || exit 1
+        else
+            ybs_build_raw $i || exit 1
+        fi
+    done
+    ;;
 
 -r|--remove)
-	check_root
-	# Remove package
-	msg_ "* Removing "
-	wmsg_ "${args[@]} "
-	for i in ${args[@]}; do
-		ypkg -C $i
-	done
-	;;
+    check_root
+    # Remove package
+    msg_ "* Removing "
+    wmsg_ "${args[@]} "
+    for i in ${args[@]}; do
+        ypkg -C $i
+    done
+    ;;
 
 --sync) 
-	# Sync pbslib via git
-	check_root
-	logfile="/var/log/ybs.log"
-	
-	if [ x"$(cat $logfile 2>/dev/null)" != x ];then
-		echo
-		mmsg "* Last update: $(date -d "1970-01-01 UTC $(cat $logfile) seconds" +%F,%T,%z)"
-		echo
-	fi
-	
-	mkdir -p $PBSLIB_PATH
-	die "Create dir $PBSLIB_PATH failed"
+    # Sync pbslib via git
+    check_root
+    logfile="/var/log/ybs.log"
+    
+    if [ x"$(cat $logfile 2>/dev/null)" != x ];then
+        echo
+        mmsg "* Last update: $(date -d "1970-01-01 UTC $(cat $logfile) seconds" +%F,%T,%z)"
+        echo
+    fi
+    
+    mkdir -p $PBSLIB_PATH
+    die "Create dir $PBSLIB_PATH failed"
 
-	if [ -d $PBSLIB_PATH/.git ]; then
-		# Already exist.
-		cd $PBSLIB_PATH
-		msg "* Sync $PBSLIB_PATH from $PBSLIB_URI"
-		msg "* Running git pull"
-		git pull 
+    if [ -d $PBSLIB_PATH/.git ]; then
+        # Already exist.
+        cd $PBSLIB_PATH
+        msg "* Sync $PBSLIB_PATH from $PBSLIB_URI"
+        msg "* Running git pull"
+        git pull 
         if [ "x$PBSLIB_BRANCH" != "x" ]; then
-    		msg "* Running git checkout"
-	    	git checkout $PBSLIB_BRANCH
+            msg "* Running git checkout"
+            git checkout $PBSLIB_BRANCH
         fi
-		date +%s >$logfile
-		exit 0
-	else
-		cd ${PBSLIB_PATH%/*}
-		ymsg "* Fetch new $PBSLIB_PATH from $PBSLIB_URI"
-		msg "* Running git clone"
-		git clone $PBSLIB_URI
+        date +%s >$logfile
+        exit 0
+    else
+        cd ${PBSLIB_PATH%/*}
+        ymsg "* Fetch new $PBSLIB_PATH from $PBSLIB_URI"
+        msg "* Running git clone"
+        git clone $PBSLIB_URI
         if [ "x$PBSLIB_BRANCH" != "x" ]; then
-    		msg "* Running git checkout $PBSLIB_BRANCH"
-	    	cd $PBSLIB_PATH
-	    	git checkout $PBSLIB_BRANCH
+            msg "* Running git checkout $PBSLIB_BRANCH"
+            cd $PBSLIB_PATH
+            git checkout $PBSLIB_BRANCH
         fi
-		date +%s >$logfile
-	fi
-	;;
+        date +%s >$logfile
+    fi
+    ;;
 
 -w|--showpbs)
-	# Show pbs file
-	for i in ${args[@]}; do
-		ybs_show $i pbs
-	done
-	;;
+    # Show pbs file
+    for i in ${args[@]}; do
+        ybs_show $i pbs
+    done
+    ;;
 
 -wr|--whatrequires)
-	msg "* [R] stand for run time depend, [B] for build, [A] for recommoneded, [C] for conflict."
-	for i in ${args[@]}; do
-		 ybs_whatrequires $i
-	done
-	;;
+    msg "* [R] stand for run time depend, [B] for build, [A] for recommoneded, [C] for conflict."
+    for i in ${args[@]}; do
+         ybs_whatrequires $i
+    done
+    ;;
 
 -h|--help|*)
-	ybs_show_usage
-	exit 0
-	;;
+    ybs_show_usage
+    exit 0
+    ;;
 esac
 
 # End of file
diff --git a/ybs-scanpackages b/ybs-scanpackages
--- a/ybs-scanpackages
+++ b/ybs-scanpackages
@@ -22,7 +22,7 @@
 . /usr/lib/ybs/funcs
 
 show_usage() {
-	cat <<EOF
+    cat <<EOF
 $0 - create packages index files
 
 Usage: $0 binary-dir
@@ -33,37 +33,37 @@ EOF
 }
 
 find_newest() {
-	local newest="$1"
-	local file
+    local newest="$1"
+    local file
 
-	for file in $@; do
-		atom_cmp $newest $file
-		if [ $? -eq 2 ]; then 
-			 newest=$file
-		fi
-	done
+    for file in $@; do
+        atom_cmp $newest $file
+        if [ $? -eq 2 ]; then 
+             newest=$file
+        fi
+    done
 
-	echo $newest
+    echo $newest
 }
 
 find_ypk() {
-	local dir all
-	
-	find -type f -name "*.ypk" |sort -u >$filelist_all
-	
-	[ "x$(cat $filelist_all)" = "x" ] && die "YPK package not found."
+    local dir all
+    
+    find -type f -name "*.ypk" |sort -u >$filelist_all
+    
+    [ "x$(cat $filelist_all)" = "x" ] && die "YPK package not found."
 
-	[ -f filelist.txt ] || touch filelist.txt
+    [ -f filelist.txt ] || touch filelist.txt
 
-	if ! diff filelist.txt $filelist_all -ur; then
-		read -p "Do you want to continue? [Y/n]" ask
-		case $ask in
-			[Nn]o|[Nn]) exit 1 ;;
-				*)
-		esac
-	fi
+    if ! diff filelist.txt $filelist_all -ur; then
+        read -p "Do you want to continue? [Y/n]" ask
+        case $ask in
+            [Nn]o|[Nn]) exit 1 ;;
+                *)
+        esac
+    fi
 
-	>$filelist_stable
+    >$filelist_stable
     find -type f -name "*.ypk" |while read i; do 
         local ypkdir=$(dirname ${i})
         if pushd $ypkdir 1>/dev/null; then
@@ -74,99 +74,99 @@ find_ypk() {
         fi
     done
 
-	# 删除空行
-	sed -i '/^$/d' $filelist_stable $filelist_all
+    # 删除空行
+    sed -i '/^$/d' $filelist_stable $filelist_all
 
-	echo "all: $(wc -l $filelist_all |awk '{print $1}')" >filelist.txt 
-	cat $filelist_all >>filelist.txt
+    echo "all: $(wc -l $filelist_all |awk '{print $1}')" >filelist.txt 
+    cat $filelist_all >>filelist.txt
 }
 
 get_info() {
-	local ypk="$1"
-	local xml="$2"
+    local ypk="$1"
+    local xml="$2"
     local uri="${ypk/$YPK_DEST\//}"
 
-	if [ ! -f "$xml" ]; then
-		local size=$(du "$ypk" -sb |awk '{print $1}')
-		local sha1=$(sha1sum "$ypk" |awk '{print $1}')
-		tar xf "$ypk" pkginfo
-		tar xf pkginfo control.xml --to-command='cat' \
-			    |sed -e '1d' -e '2d' -e '$d' -e '/<uri>/d' \
-			    |sed -e '/\<build_date\>/a\   <size>'"$size"'<\/size>' -e '/\<build_date\>/a\   <sha>'"$sha1"'<\/sha>' \
-			    -e '/\<build_date\>/a\   <uri>'"$uri"'<\/uri>'
-		rm pkginfo
-	else
-		cat $xml |sed -e '1d' -e '2d' -e '$d' -e '/<uri>/d' \
-		         |sed -e '/\<build_date\>/a\   <uri>'"$uri"'<\/uri>'
-	fi
+    if [ ! -f "$xml" ]; then
+        local size=$(du "$ypk" -sb |awk '{print $1}')
+        local sha1=$(sha1sum "$ypk" |awk '{print $1}')
+        tar xf "$ypk" pkginfo
+        tar xf pkginfo control.xml --to-command='cat' \
+                |sed -e '1d' -e '2d' -e '$d' -e '/<uri>/d' \
+                |sed -e '/\<build_date\>/a\   <size>'"$size"'<\/size>' -e '/\<build_date\>/a\   <sha>'"$sha1"'<\/sha>' \
+                -e '/\<build_date\>/a\   <uri>'"$uri"'<\/uri>'
+        rm pkginfo
+    else
+        cat $xml |sed -e '1d' -e '2d' -e '$d' -e '/<uri>/d' \
+                 |sed -e '/\<build_date\>/a\   <uri>'"$uri"'<\/uri>'
+    fi
 }
 
 merge_info() {
-	local filelist="$1"
-	local xmlfile="$2"
+    local filelist="$1"
+    local xmlfile="$2"
 
-	echo '<?xml version="1.0" encoding="UTF-8"?>' >$xmlfile
-	echo '<PackageInfo>' >>$xmlfile
+    echo '<?xml version="1.0" encoding="UTF-8"?>' >$xmlfile
+    echo '<PackageInfo>' >>$xmlfile
 
-	cat $filelist |while read ypk; do 
-		xml=${ypk%.ypk}.xml
-		if [ ! -f "$xml" ]; then
-			echo '<?xml version="1.0" encoding="UTF-8"?>' >$xml
-			echo '<PackageInfo>' >>$xml
-			get_info ${ypk} >>$xml
-			echo '</PackageInfo>' >>$xml
-		fi
-		get_info ${ypk} ${xml} >>$xmlfile
-	done
+    cat $filelist |while read ypk; do 
+        xml=${ypk%.ypk}.xml
+        if [ ! -f "$xml" ]; then
+            echo '<?xml version="1.0" encoding="UTF-8"?>' >$xml
+            echo '<PackageInfo>' >>$xml
+            get_info ${ypk} >>$xml
+            echo '</PackageInfo>' >>$xml
+        fi
+        get_info ${ypk} ${xml} >>$xmlfile
+    done
 
-	echo '</PackageInfo>' >>$xmlfile
-	
+    echo '</PackageInfo>' >>$xmlfile
+    
 }
 
 final() {
-	cp stable.xml update.xml
-	tar cJf stable.tar.xz update.xml
-	
-	rm update.xml
+    cp stable.xml update.xml
+    tar cJf stable.tar.xz update.xml
+    
+    rm update.xml
 
-	>updates.list
+    >updates.list
 
-	for i in stable.tar.xz; do
-		name=${i}
-		date=$(date +%s)
-		sha1=$(sha1sum $name |awk '{print $1}')
-		echo "$name $date $sha1"  >>updates.list
-		sleep 1
-	done
+    for i in stable.tar.xz; do
+        name=${i}
+        date=$(date +%s)
+        sha1=$(sha1sum $name |awk '{print $1}')
+        echo "$name $date $sha1"  >>updates.list
+        sleep 1
+    done
 
-	date +%s >updates.date
+    date +%s >updates.date
 }
 
 # main
 #
 
 if ! which ypkg >/dev/null 2>/dev/null; then
-	die " ypkg is required, please install ypkg2"
+    die " ypkg is required, please install ypkg2"
 fi
 
 if ! which diff >/dev/null 2>/dev/null; then
-	die " diff is required, please install diffutils"
+    die " diff is required, please install diffutils"
 fi
 
 case x$1 in
-	x*h|x*help) show_usage
-	            exit 0
+    x*h|x*help) show_usage
+                exit 0
 esac
 
 case x$# in 
-	x0) YPK_DEST=$YPK_DEST;;
-	x1) YPK_DEST=$(readlink -f $1) ;;
-	x2|*) show_usage
-	    exit 0
+    x0) YPK_DEST=$YPK_DEST;;
+    x1) YPK_DEST=$(readlink -f $1) ;;
+    x2|*) show_usage
+        exit 0
 esac
 
 if [ ! -d $YPK_DEST ]; then
-	die " $YPK_DEST not found."
+    die " $YPK_DEST not found."
 fi
 
 filelist_all="/tmp/.filelist-all"
